### ISSUE TITLE
string_tooltip_reloadModsFromLibrary

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#12]
trying to think as a user here and when translating in general, so here goes.

https://github.com/ME3Tweaks/ME3TweaksModManager/blob/50d3327f5894c9df31b40e64e59d71e373c11405/MassEffectModManagerCore/modmanager/localizations/int.xaml#L196

The concept of "library" must be made very clear and chosen for either "left half of m3" or "some folder on your HDD". I'd use library for the former.

In this case I find the description unclear and would propose "Reload mods from HDD" or "Reload library from HDD".

I feel like "reload" implies throwing away the current index and rebuilding it from HDD, i.e. discovering new Mods. If that's the case, great.
Alternatively, if reload is done based on current index, I'd say refresh might be more fitting.

PS: maybe there's a better word instead of HDD (SSD nitpicking) that has equally intuitive meaning unlike "storage".

**Comment by Mgamerz** [comment]
When you reload mods from library, it dumps all existing mods from the left list and scans all mods from the your library directory. IF one is not set, it defaults to a subdirectory called "mods" next to the executable. In here are three folders: ME1/ME2/ME3, and moddesc.ini files are looked for in subdirectories of each of these folders. It loads in order of ME3=>ME2=>ME1.

**Comment by HarHarLinks** [comment]
I agree available Mods should be changed to Mod Library.
This string could maybe be "Reload mods from disk".
