### ISSUE TITLE
string_installationTarget localization not applied

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#13]
string_installationTarget is not applied in current build 103 preview (as of Sun Dec  1 03:17:17 UTC 2019)

![image](https://user-images.githubusercontent.com/2803622/69908845-8f460c00-13f1-11ea-8392-14efd5f605ef.png)

**Comment by Mgamerz** [comment]
it should be applied on reload, however I just fixed this so it will update when you switch languages.
