### ISSUE TITLE
string_installationTarget

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#14]
see also many related strings.

The term of "(installation) target" makes sense if you have a certain knowledge of what's going on, but might be confusing otherwise. Most people will have one "target" per game at most.

How do other mod managers handle this?

Are there existing ideas? Did CreeperLava have a suggestion?

**Comment by Mgamerz** [comment]
Closing this as it is described in tutorial in 6.1
