### ISSUE TITLE
Cross-Platform Work?

### ISSUE THREAD

**Issue by ThisNekoGuy** [ME3Tweaks/ME3TweaksModManager#140]
Was just wondering if it would be possible to make ME3Tweaks cross-platform with Linux by using Godot as a front-end and adapting the backend for native support for Linux Proton users of the trilogy?

**Comment by mirh** [comment]
What has a 3D engine to do with a modding tool? Not like there's anybody reimplementing the whole unreal engine here. 

For a native version of anything from ME3Tweaks (putting aside that I don't really see the point.. it's not like you wouldn't still need wine for UDK or the base games) .NET 5 may probably easily allow that. 
Otherwise you should be just fine already with `dotnet48` and [this](https://bugs.winehq.org/show_bug.cgi?id=45871#c6).

**Comment by Mgamerz** [comment]
I already rewrote mod manager from java into C# (on .NET Core 3) and that took almost a year. The java version technically could run under Linux but it used a lot of native functionality. In fact it was originally built on Mac OS X before my MacBook decided to bootloop itself.

As Mirh has pointed out, running things on Wine and such should work. I have no plans to make a Linux version of Mod Manager. There may eventually be a Linux version of A LOT Installer as I have been working on something like that as a side experiment, but the userbase of Linux for any of my apps is less than .1% so it is not really justifiable unless it’s an experiment like it was for ALOT installer.

**Comment by ThisNekoGuy** [comment]
To be clear, Godot is capable of crating software too, in fact, Godot itself was actually _made in Godot_.
Regardless, that's slightly disappointing but understandable.
(I've attempted to use Mass Effect mod managers in Wine before but with little or poor success. Can't 100% remember if it was this one or another one.)

**Comment by ThisNekoGuy** [comment]
@mirh Also, I attempted your suggestion and it didn't work

**Comment by mirh** [comment]
You did install the dotnet48 verb and you did use the d3dcompiler_47.dll workaround, and the thing still isn't starting?

**Comment by ThisNekoGuy** [comment]
Using Proton specifically to do this, with the intention to launch the games through ME3TMM, yes.
For whatever reason, ME3TMM just doesn't agree with Proton but does with an existing .NET 4.7.1 Lutris install that I used for testing. (And having DXVK enabled makes the manager's window render a transparent copy of wherever the window spawns.)

(I'm also trying to do it through Proton (using a script I have that tricks Steam into thinking the game is active but launches a different executable instead because the mod manager claims to make sure that textures are loaded with the correct LOD when the games are launched through it.)

**Comment by ThisNekoGuy** [comment]
I had actually ran ME3TMM and ALOT on ME1 & ME2 in a Windows install and have them both accessible to run (and the MyDocuments folder) from my Linux install (though this wasn't my first choice, believe me) so that all I had to do was just run the games through ME3TMM in Proton :/

**Comment by mirh** [comment]
Then DXVK is the problem, understandably considering it has always been kind of a hack with anything that isn't pure 3D.

**Comment by mirh** [comment]
That was fixed today
https://github.com/doitsujin/dxvk/issues/2732
