### ISSUE TITLE
Game restore utility does not delete TexturesMEM*.tfc files

### ISSUE THREAD

**Issue by JaredHonda** [ME3Tweaks/ME3TweaksModManager#156]
As reported via Discord:

### Summary
Game backup utility allows existing TexturesMEM*.tfc files to be backed up. These files then remain in the game directory, which triggers a warning for the ALOT V4 installer leaving them after a restore and causing ALOT v4 installer to detect modded files and fail to install textures.

### Background
When using the preview version of the ALOT v4 installer for ME2, a warning modal appears telling the user that their game files have been modified and must be rolled back to a vanilla state, even when starting from a backup created via ME3Tweaks MM. Attempting the same operation using the v3 installer produces no such warning and textures are applied without issue.

@Mgamerz provided instructions to check for TexturesMEM*.tfc files in the Mass Effect 2/Biogame/CookedPC folder for .tfc files, which produced these results:
![image](https://user-images.githubusercontent.com/25514253/96287824-1a97a400-0fa8-11eb-860e-d76fc24013ca.png)

### Problems identified

- Original ME3Tweaks MM backup/restore utility for ME2/ME3 should not back up existing TexturesMEM*.tfc files present in the game directory during the backup operation.
- ALOT v3 installer fails to detect the presence of any TexturesMEM*.tfc files (which should not exist, to allow a clean texture installation). It allows the user to mistakenly proceed with installing textures.

The game runs successfully without any problems on my system even after using the v3 installer, but that is not a valid test since it's an early playthrough and problems could appear later on.

### Version information

- ALOT 3.0.587.5615
- ME3Tweaks Mod Manager 6.1.3, Build 111
- Windows 10 Home build 19041.572
- AMD Ryzen 7 3700X, 32 GB DDR

**UPDATE:** edited issue description to clear up confusion that it's the initial backup operation that has a problem, not the restoring of a game directory.

**Comment by Mgamerz** [comment]
The issue is that it allowed these files to be backed up. It's not that they weren't deleted. They are part of your backup, but the code should have prevented this from happening when performing backup checks.

**Comment by Mgamerz** [comment]
The backup check should now find these MEM TFC files when making a backup. This was part of 6.1.4.
