### ISSUE TITLE
indicate that Discord is in English

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#16]
I already implemented it this way in deu.xaml:

Because Discord is only in English, indicate it in non-english localizations.

For example:
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/50d3327f5894c9df31b40e64e59d71e373c11405/MassEffectModManagerCore/modmanager/localizations/deu.xaml#L160

**Comment by Mgamerz** [comment]
I think this would be better in the welcome panel, because there is a ton of strings that say come to the discord - pretty much every unexpected error.

**Comment by Mgamerz** [comment]
In this case it'd be part of string_previewPanelIntro

**Comment by HarHarLinks** [comment]
I have it everywhere discord is mentioned for now, which might be overkill tbh - or not
