### ISSUE TITLE
string_selectGameExecutable and related

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#17]
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/50d3327f5894c9df31b40e64e59d71e373c11405/MassEffectModManagerCore/modmanager/localizations/int.xaml#L174

Let me precede this by saying that i'm not sure if this might be a non-issue in English.

From my experience, German users have no idea what "executable"/it's translated equivalent is. However if you speak of an ".exe (file)" it is usually clear to people.

Thus I suggest:
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/50d3327f5894c9df31b40e64e59d71e373c11405/MassEffectModManagerCore/modmanager/localizations/deu.xaml#L174

**Comment by Mgamerz** [comment]
This is used as title of a dialog when adding targets.

![image](https://user-images.githubusercontent.com/2738836/70675802-6fabb080-1c47-11ea-9dca-145edb3c30ce.png)

**Comment by HarHarLinks** [comment]
That doesn't really clear this up for me.

**Comment by Mgamerz** [comment]
Sorry, posted wrong screenshot.
![image](https://user-images.githubusercontent.com/2738836/70676608-fd889b00-1c49-11ea-8428-41e091059894.png)
