### ISSUE TITLE
[MEIM?] Make an option for independent dubbing/subbing/UI

### ISSUE THREAD

**Issue by mirh** [ME3Tweaks/ME3TweaksModManager#173]
**Is your feature request related to a problem? Please describe.**
Well, ME1RE being english-only kind of gave me the idea, but I guess this is very much orthogonal to it. 

**Describe the solution you'd like**
By [editing](https://www.reddit.com/r/masseffect/comments/bepvq4/mass_effect_1_dlc_english_audio_subtitles_in/el7rvlf/) [FileIndex.txt(s)](https://forum.worldofplayers.de/forum/threads/1317942-Umstellen-auf-Englische-Sprache-und-Deutschen-Text#post22159856) (which is some kind of ancestor to PCConsoleTOC?) it should be possible to shoehorn separate locales without touching any other actual content file. 

**Describe alternatives you've considered**
`[Engine.Engine]Language` only seems able to change the entire game localization in bulk. 
And I guess like the [old](https://www.gamepro.de/xenforo/threads/mass-effect-englische-sprachausgabe-mit-dt-untertiteln.114405/) usual [solution](https://www.pcgamingwiki.com/wiki/Dishonored#Independent_UI_and_dubbing.2Fcaptioning) to disguise file names back and forth in the right folder is still valid but it's somewhat "messier" imo (and idk if some mod couldn't be sensitive to that). 
I'm also usually a fan of the transparency batch files afford for such menial tasks, but stream editing with Windows native tools is masochism. 
So a "proper program with bells and whistles" would seem the right conclusion at this point. 

**Additional context**
I get this isn't really about "inis" anymore (unless you can still find some easy peasy variable like in ME2?), but idk what better place for it.

**Comment by Mgamerz** [comment]
I'm not sure what you mean. Localizations are available in the TLK file, in ME1 it has multiple languages in the same file. To localize it, it would need to have that file updated.

**Comment by mirh** [comment]
Check the links I posted. 
When I say "independent" I mean playing with the italian dubbing with english subtitles and a french UI (as a very extreme example). 
I know it can be done *at least* in the ways I mentioned above, there should be no need to touch tlks (though I'm open to better ideas).

**Comment by mirh** [comment]
https://www.pcgamingwiki.com/wiki/Mass_Effect#Independent_UI_and_dubbing.2Fcaptioning
Ok, I'm actually surprised by just how effective tricking with GlobalTlk.upk has been. 
(though I'm wondering if you couldn't force it inside an .ini like instead happens with the DLCs autload)

Still, be it manually editing FileIndex.txt, or manually renaming/symlinking files all over the Maps and Dialog folders.. it'd be a chore nonetheless. 
I hope with those examples you can better understand what I wished could be done automagically.

**Comment by mirh** [comment]
> unless you can still find some easy peasy variable like in ME2?

Well, it [turns out](https://www.pcgamingwiki.com/wiki/Mass_Effect_2#Changing_language) the only time `VOLanguage` was ever reported to actually work was in the Polish game build. 
Do you know if it's possible to rehook its functionality with other languages/editions, or is it the usual native code magic?

**Comment by Mgamerz** [comment]
As this is now officially supported in Legendary Edition, I'll be closing this, as I'm not really interested in adding new features for OT, as the majority of development is now focused on LE.

**Comment by mirh** [comment]
Not going to question your bent, but are you sure this is actually fulfilled for LE?

My feature request isn't just about having a "general" toggle for language, and profit. 
But untangling UI, audio and subtitles from each other.

**Comment by Mgamerz** [comment]
In LE you can choose to have English voice with French text. There is no
difference internally to the game of UI vs subtitles, it's all just one
localization source.

**Comment by mirh** [comment]
Uhm.. Right, that's the unified design adopted by the engine from ME2 onwards. 
And since the June 7th patch took care of adding GUI toggles (I can only imagine that's just a simple build-in override of the TLK?), there really isn't much more that can be done there. 

Could you still give a quick skim to my PCGW instructions?
Even just from a "piece of *your* mind" prospective, should I prefer FileIndex meddling, files renaming or is either eventually just as good and "safe"? 
How about instead my symlinking trick to avoid messing with the steam/origin file integrity gods?

**Comment by Mgamerz** [comment]
FileIndex meddling won't work if you use any mods are we always rebuild the fileindex file on game boot. Symlinking requires admin rights (or changing some windows settings), and it also doesn't work with texture tools (they ignore symlinks). I think you'd just have to rename the files around.

**Comment by mirh** [comment]
[Right](https://github.com/SirCxyrtyx/ME1-DLC-ModEnabler) (so it couldn't even be just a matter of "first mod, and then do the trick")
..and I'm ashamed I missed the privileges detail. 

So, excluding a dubbing switch DLC mod, the second-best thing is good old file swap indeed (at most still through the *Published* folder in order to keep somewhat cleaner the game folders.. putting aside I don't think any mod touches dialogs)
I'll try to repurpose the batch file they made during the first days of MELE.

**Comment by Mgamerz** [comment]
If you use the Published folder, it’s pretty much a guarantee it won’t work with any modding tools, which in fact might just break the game. From: mirhSent: Tuesday, November 16, 2021 8:03 PMTo: ME3Tweaks/ME3TweaksModManagerCc: Mgamerz; State changeSubject: Re: [ME3Tweaks/ME3TweaksModManager] [MEIM?] Make an option for independent dubbing/subbing/UI (#173) Right (so it couldn't even be just a matter of "first mod, and then do the trick")..and I'm ashamed I missed the privileges detail.So, excluding a dubbing switch DLC mod, the second-best thing is good old file swap indeed (at most still through the Published folder in order to keep somewhat cleaner the game folders.. putting aside I don't think any mod touches dialogs)I'll try to repurpose the batch file they made during the first days of MELE.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
