### ISSUE TITLE
string_selectModArchive and related

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#18]
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/50d3327f5894c9df31b40e64e59d71e373c11405/MassEffectModManagerCore/modmanager/localizations/int.xaml#L173

In many cases it is clear by context that archive means a .7z/.rar/.zip file. In this and some other cases, I fear it might not be.

**Comment by Mgamerz** [comment]
Many of these strings are context sensitive. For example this string is used as the title of a file picking window.

**Comment by Mgamerz** [comment]
This string is only used as the title of a file picker dialog that shows up after you specifically choose the menu item to import 7z/rar/zip.

![image](https://user-images.githubusercontent.com/2738836/70675737-43902f80-1c47-11ea-90ac-efa5839159da.png)

As such, this is the correct use of the string.
