### ISSUE TITLE
6.2 - SFXGame.BioDeprecated reference errors

### ISSUE THREAD

**Issue by beccatoria** [ME3Tweaks/ME3TweaksModManager#180]
Deploying a mod for ME3 is picking up reference errors for SFXGame.BioDeprecated, which is defined in SFXGame.pcc.  Per discord discussion this is likely not a true error and can be ignored.

I've attached the error text (for vanilla and Genesis 2 Biop_Char.pcc files).  

[me3tmm-errors.txt](https://github.com/ME3Tweaks/ME3TweaksModManager/files/5700781/me3tmm-errors.txt)

**Comment by Mgamerz** [comment]
I've fixed this in my local code. It's because BioDeprecated only inherits from Object. It seems like it was allowed to be set as a placeholder in Unreal for some reason.
