### ISSUE TITLE
Remember selected Installation Target for next session

### ISSUE THREAD

**Issue by Herobrine24** [ME3Tweaks/ME3TweaksModManager#181]
I recently started launching the games through the manager, however I dont always remember to switch the target when im doing a playthrough of ME1/2.

If the Manager could remember what Target was chosen last time, it would be much easier to simply fire it up and click "Start Game" without having to close the wrong game and then select the correct game in the Manager.

**Comment by Mgamerz** [comment]
Mod Manager should default to the current active target, which is defined in the registry. Changing the dropdown should prompt you for admin rights, which is what changes the registry. If you decline this, it will not remember.

**Comment by Herobrine24** [comment]
It always defaults to ME3 on my end.
Im not sure if I ever was prompted for admin rights when i clicked on the dropdown.
Running it as Administrator doesn't solve it either.

**Comment by Mgamerz** [comment]
Do you mean it auto starts with ME3, rather than ME2? I was talking about multiple targets for a single game. It sounds like you are talking about just 3 normal targets, one for each game, but the default selection is ME3.

**Comment by Herobrine24** [comment]
I mean the general installation target at the top which also determines which game will be launched when you press "Start Game"

**Comment by Mgamerz** [comment]
This should be fixed in the latest beta build.
