### ISSUE TITLE
Application Launch Error for Steam games on direct launch, sometimes

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/ME3TweaksModManager#191]
Well, they *at least* put an error message returning codes in the first place, so there's that..
I'm not sure for that 65432 offset, anyhow that should mean `ERROR_FILE_NOT_FOUND` (`Steam.dll` I think).

_Originally posted by @mirh in https://github.com/ME3Tweaks/ME3TweaksModManager/issues/179#issuecomment-740226373_

**Comment by Mgamerz** [comment]
I have ME1/ME2 on steam now and I'm trying to replicate this issue. Steam has the concept of libraries, in that you can't just point to a location to install the game, it must be done under a library, which houses a lot of other files (including a folder with steam.dll).

I'm in the process of testing things, but I will document my findings here.

1. Running Mass Effect 2 directly from the executable, from from a newly made Steam Library folder, without running it through Steam yet, yields an error message.
![image](https://user-images.githubusercontent.com/2738836/103178673-127aa100-4842-11eb-93ec-e555cde722c7.png)

2. Running Mass Effect 2 directly from the executable, from the new steam library folder,r AFTER running it through steam (and it ran), yields the same message.
![image](https://user-images.githubusercontent.com/2738836/103178705-68e7df80-4842-11eb-9668-16929dbccdde.png)

**Comment by Mgamerz** [comment]
Shortly before the app closes, it seems to be looking for steam.exe in the parent paths. 
![image](https://user-images.githubusercontent.com/2738836/103178782-40141a00-4843-11eb-858f-8ac7f4477ee1.png)

This fails because Steam is installed on a different drive.

**Comment by Mgamerz** [comment]
Doing some research with ProcMon and Process Hacker, I can see there is a different in environment variables for the steam launch process.

When run directly from the exe:

![image](https://user-images.githubusercontent.com/2738836/103179082-ae59dc00-4845-11eb-8932-cff00786a971.png)


When run from steam:
![image](https://user-images.githubusercontent.com/2738836/103179110-dba68a00-4845-11eb-8fe4-45cad42e02a3.png)

When invoking a process it is possible to set these values. I'm going to see if I can write some of them in on Mod Manager launch of the game to see if it fixes the issue.

**Comment by Mgamerz** [comment]
Doing some more digging. If Steam.exe is not running, the app will not run, regardless of you setting these keys. It seems in this case, it looks up the parent dirs for Steam.exe, like you described in the other thread.

If it finds it - regardless if it is signed by valve - it will run that executable with parameters `-applaunch <gameid>` and then exit. That's not really helpful for us as it does not give us control of which game will be run.

**Comment by mirh** [comment]
I applaud all this research effort (there's [this](https://partner.steamgames.com/doc/features/drm) and [this](https://github.com/Reloaded-Project/reloaded.universal.steamhook) btw).. But I'm not sure what's the point?
Steam DRMed games are meant to be run from steam, end of story. If you don't want that you should use steamless if really really any, what am I missing?

**Comment by Mgamerz** [comment]
If I clone the game (say I want two installs - one modded with textures, one not). With Origin this is easy because it just boots whatever is listed in the registry key under BioWare/Mass Effect (2/3). Steam seems like it requires to be running or it will throw the application error, which users then attribute to my software, when it's really not my software.

There's some registry keys steam seems to set `HKEY_CURRENT_USER\Software\Valve\Steam\ActiveProcess` for `pid` and `activeuser`, that seem to indicate the status of the steam client, if it is running and logged into. While not 100% reliable for pid (if steam was forcibly terminated, then uninstalled or something, it could be misleading, but that's very unlikely), it seems to be useful for telling if the client is logged in, which will let me launch steam.exe, wait for a bit (I'm doing 20 seconds maximum for activeuser to change from 0 to a non-zero value, which occurs when steam boots), and then launching the game. This should reduce, but not 100% eliminate, these application error messages that users think my app is throwing. 

I also am having it just install the steamappid text file, which will make it slightly more reliable for users who run it manually for some reason. I can't obviously make steam be running for them but it might help someone (probably me, who scripts game launches from terminal when testing things like asis).

**Comment by mirh** [comment]
I'm not really sure what's "obvious" here. 
First of all, why couldn't you check if some steam.exe process is running? 
(or if you want to do it properly, you could even add a dependency to the steam api, like even some graphical mods for other games do)
Secondly why don't you just start the game with `steam://rungameid/17460` if you detect its flavour?

And last and not least.. this is kind of the downside of "big monolithic" switches rather than just replicating the "deltas", isn't it?
I guess like if you are a big beefy modder, this may actually save you some time, but I believe normal folks would rather appreciate "compact backups" (i.e. something comparable to the `Published\CookedPC` override from the documents folder, if it actually worked like expected)

**Comment by Mgamerz** [comment]
Do you know what the exact path of the executable the invocation of  `steam://rungameid/17460` is going to run? If I make a game copy in Mod Manager, steam will not know there is two copies of the game that I want to boot at any time. To get steam to accurately boot, I now how to modify a bunch of steam files in order to get the right executable to boot, which is something I don't want to do. Doing it for Origin ME games is fine because the ME keys don't affect other Origin things and for the most part are just tangential to origin.

Just because steam is running does not mean it is logged in (it could be logged out, or not started up yet). Until you know it's logged in, running the game is kind of a crapshoot. Also, getting the process list in c# is an expensive task, taking several hundred milliseconds (which doesn't sound like a lot, until you query it a lot).

In MM5 and below there was 'incremental' backups which only took backups of files that were modified by the tool. The problem is people also modify the game outside of the tools, which means that system stops working very quickly. Supporting that system was also a lot of work, and would not work in the examples presented in this thread anyways.

**Comment by mirh** [comment]
> Do you know what the exact path of the executable the invocation of steam://rungameid/17460 is going to run?

Lacking any other information in this regard, my educate guess is just that the client keeps in memory a table with the results of its initial query. 
So you may want to try editing appmanifests ("installdir" seems like a good start). 

> steam will not know there is two copies of the game that I want to boot at any time.

That actually sounds good, considering two copies of the same game would _really_ annoy it. 

> (it could be logged out, or not started up yet)

Then if you really really really want to be this anal, I can just recommend [this](https://github.com/rlabrecque/Steamworks.NET). You fight fire by being fire yourself. 

> The problem is people also modify the game outside of the tools

I think you are overthinking it. 
If you are a modder (as in, a content producer), then it's not really like you are going to mind if some "spoonfeeding" is missing. 
If you are an average joe, then you sure aren't going to touch anyway else the game. 

> [tool] which only took backups of files that were modified by the tool.

... 
Ehrm, I'm not really sure how to state this, but I feel like your brain must be overloaded by stress or something if you worry about such tautologies. Are you sure you are straining yourself?

**Comment by Mgamerz** [comment]
Here is my list of current targets:

![image](https://user-images.githubusercontent.com/2738836/103181745-cb9ca380-4861-11eb-815f-ad9f7ebc7d2e.png)

As I am also a user of my software, it needs to able to serve my needs too. I need to be able to have multiple copies of pretty much every game because I need to be able to test many scenarios. I do not want to worry about what game steam is actually going to decide to boot, I want it to boot the one listed in the dropdown when I click start game.

There are many users (support discords from public modding server, my server, alot server, nexus comments that have diagnostics all show this) show many users still manually install things, such as binkw32, DLC mods, and some older mods such as Arrival Triggering Mod that directly install into game files rather than as an overriding DLC mod). There are also some other modding tools that aren't really under my control such as MEUITM/MEUITM2 installer that don't have any concept of backing up. Many features of Mod Manager depend on vanilla backups, and ME3Explorer even now uses the backups for modding now, such as when comparing information against modded vs vanilla files.

**Comment by mirh** [comment]
Yes, I understand. 
But a tool can only be eventually responsible for what the tool itself does. 
If somebody decides to do modding "their own way", then they are responsible for that. 

***If*** you want "a quick way to launch between enormously different games versions" that's totally legit, but then it's also somewhat tangential to backups, which could happen in a thousand and one different ways (hell, you could even have specific files be downloaded anew from the [official](https://github.com/SteamRE/SteamKit) [servers](https://github.com/Imposter/otool))
You could still have a "master backup folder" even though "target switching" only happens at a file or .ini level (like, again, I'm not totally sure on the magic behind DLCModules, SeekFreePCPaths, FileIndex and whatnot, but I feel the potential is there)

*Sooo*, anyway, back on track of a single topic at time.. `steam_appid.txt` (it was exactly created for these "dev" enviroments after all) plus a very simple steam api check sounds like the simplest most comprehensive solution.

**Comment by Mgamerz** [comment]
My solution is essentially just make sure steam is running, check the registry key for logged in (if after 20s it does not show as logged in, just continue anyways). I'm not sure if I want to run it in silent mode or not. I would like to have it run the 'connecting account', but without the store page showing up, but not sure that's possible. I could not see a command line argument to suppress the store but keep the login flow.

On a sidenote, I was working on trying to fix or workaround the issue of launching ME2 and getting this when it's Origin based:
![2020-12-27_20h23_06](https://user-images.githubusercontent.com/2738836/103192475-07e9f700-4896-11eb-8d49-a37e3da364aa.png)

ME2 does not invoke origin like ME3 so this happens a lot and is pretty annoying. I read some of your research findings (collection of links) about the topic and found a very obvious ME2 DRM analysis, very interesting read, way over my head. Maybe someday ;)

Anyways, after doing few hours of research and pulling up some ancient ME3Explorer code I found I can run ME2 through origin without having to deal with trying to guess the localized game ID by passing it through origin://launchgame/<id string> (https://gaming.stackexchange.com/a/330629/26981). I knew you could launch games this way but I did not realize you could pass multiple IDs (I wrote a blog post about this in like 2014 trying to learn about the protocol). They now use origin2:// with offer IDs but they're localized SKUs, which suck. The content IDs are baked into the installerdata.xml, but I'm finding just reading them out of the PAR file is actually more useful (and probably more reliable, as users cannot edit these easily). 

Using this info I can build a URL that is keyed to the local files regardless if it's a different version we don't know about. E.g. here's my ME2 link: 

origin://launchgame/1003291,1005288,1003290,mass_effect_2_de,mass_effect_2_dd,mass_effect_2_fr,mass_effect_2_it,mass_effect_2_pl,mass_effect_2_ce 

I found when running this, origin would come up with the right game but then the game would immediately exit. After bashing my head for a few hours on it I figured out it's actually the MassEffect2.exe stub exiting immediately, with Origin and without. ME2Game.exe ran fine - which is the same problems that have been reported for years - just run ME2Game and not MassEffect2.exe. The problem here is that Origin does not run ME2Game, it runs MassEffect2.exe. I want to avoid this licensing page, so I need to have it run through Origin.

After doing a tiny bit of sleuthing I determined that MassEffect2.exe is looking to load ME2Game.exe... by doing some weird lookup as I show here: https://twitter.com/Mgamerz/status/1343432877069934592

After looking at the 'Path' item in regedit, it was missing a trailing slash. The DRM code must not have checked for a trailing slash... Trusting the setup too much, I think. As soon as I fixed the trailing slash, it worked. I looked at my mod manager code and it did not set a trailing slash. After updating it, changing targets makes ME2 work flawlessly now. I'm not sure if Origin still uses Install Dir to determine which game to run, or if uses Path, I would need to do further work to find out.

**Comment by mirh** [comment]
> My solution is essentially just make sure steam is running, check the registry key for logged in

Mhh.. really, why can't you just use the steam api?
You could even detect the mindblowing scenario where the user was logged in with an "unauthorized" account. 
https://partner.steamgames.com/doc/api/steam_api#SteamAPI_Init
https://partner.steamgames.com/doc/api/ISteamApps#BIsSubscribedApp

> The cached license expiration seems really short so it feels like just a few days until it expires. 

Lolwat? You must have a problem on your end. 
Unfortunately I did force refresh mine just around this summer for reasons, but I'm pretty sure it had been standing for a good 5-6 years before that. 

> They now use origin2:// with offer IDs but they're localized SKUs, which suck.

Admittedly I'm also saying this because I haven't really found any definitive solution, but I don't think you are really supposed to go through origin here. 
The client/installation itself seems to register the game to be launched directly from the exe. 

> 1003291,1005288,1003290

Maybe I'm wrong, but my very very half assed guessing is that these aren't about localization. They are different game editions. 
1005288 should be the free "on the house" giveaway they had. 
1003290 should be the standard edition
1003291 should be the deluxe edition. 
(what do you have in `HKLM\SOFTWARE\Wow6432Node\Origin Games`?)

> After looking at the 'Path' item in regedit, it was missing a trailing slash. The DRM code must not have checked for a trailing slash... 

I think the question should be why the slash was missing in the first place..
My `bioware\mass effect 2` entry has it, and I don't recall ever having problems. 
Perhaps you just mishandled editing (understandably, considering funnily enough the ME1 entry *does not* have the slash instead)

**Comment by Mgamerz** [comment]
If I do not boot me2, it requires me to run it again within about a week.

**Comment by mirh** [comment]
Without you touching its stuff (folders, regkeys, files) whatsoever?

**Comment by Mgamerz** [comment]
As far as I am aware, yes. For example I have Origin version of ME2 on my laptop. I almost never run the games on it since it's got an anemic GPU but sometimes I do when I need to do something and am too lazy to be on my desktop. Launching from Mod Manager has almost almost never worked, giving me this logon prompt. Until a few days ago I never had a second copy of ME2 (I didn't have the space). The path thing is possibly due to mod manager, but the prompts seem to be due to other things. The DRM post didn't seem to indicate file pathing. I'll try to test it (or find someone who can).

**Comment by mirh** [comment]
DLCs don't use that license system, AFAIK they only rely on BioPersistentEntitlementCache.ini. 
And funnily enough mine is called `mass_effect_2_ce.dlf` (Collector's Edition perhaps? Which was actually my first purchase of the game). 

In the registry I have all three of those numbers, but for reasons their display name is "Mass Effect™ 2 Digital Deluxe Edition"
The quickbms guys provides a [different explanation](https://aluigi.altervista.org/papers/origin_pids.txt), but I wonder if that isn't just a situation like steam and bundles (which can carry different appids). 

> As far as I am aware, yes.

Then I'm afraid your "maybe someday DRM analysis" is scheduled to happen earlier than expected. 
I can absolutely assure you that is not normal.

**Comment by mirh** [comment]
https://yingtongli.me/blog/2018/12/02/drm1-3.html
Lool, so.. assuming for simplicity that your desktop is just FUBAR because reasons, could the problems on your laptop have something to do with optimus?
At least a slightly newer version of the DRM was using *EnumDisplayDevicesW* in the machine hash, which sounds to me [weak enough](https://bugs.chromium.org/p/chromium/issues/detail?id=106438#c4) to be changing left and right with switchable graphics.

**Comment by Mgamerz** [comment]
My system does not have a discrete GPU at all. While it would be fun and interesting to do DRM research I don't have the time (or know how, really) to do it. Not to mention I would likely not include it since it becomes legally questionable.

I've added a (hidden for now) option to launch games through Origin that are Origin-based (ME1/ME2). This will also provide the benefit of tracking play time, which some users like. Likely will not be in 6.2.0 release.

**Comment by mirh** [comment]
Nobody is saying to bypass DRM. Just to understand why somehow it invalidates your token so often. 
If the gpu isn't it, then I cannot really see anything else in its "equation" being shaky (though perhaps older versions used something more or less).

**Comment by mirh** [comment]
> I think the question should be why the slash was missing in the first place..

Ok, I have an answer: fucking origin writes the value like it was "Install Dir", with the trailing space. 
While fucking steam just writes "%INSTALLDIR%" and that's it. 

I also just now figured out, this made my "one-liner cmd fix for admin privileges" completely break.

**Comment by RunasSudo** [comment]
> EDIT: @RunasSudo would you happen to know any way the dlf license system could trip without any actual major hardware change?

My write-up is for a game older than ME2 so it's possible the DRM system works differently (AFAIK certainly by the time ME3 rolled around the DRM had changed a bit). Based on the version in my post, it doesn't seem likely to me that the hardware fingerprint would change without any changes to hardware configuration. There is a time-based expiry (stored in one of the files I  discussed, but I don't have any of those on me at the moment) though I don't recall the duration.

**Comment by mirh** [comment]
I only see a "GrantTime" and a "StartTime" in your file. And even [newer](https://www.unknowncheats.me/forum/battlefield-4-a/169865-battlefield-4-blaze-emulator-83.html#post2258592) versions seem to still just use that. 

And that matches my own experience, as I hinted a couple of message above. The token should last forever AFAIK.

**Comment by mirh** [comment]
https://stackoverflow.com/questions/36031744/regular-win10-updates-change-serialnumber
https://docs.microsoft.com/en-us/answers/questions/200428/wmi-windows-serial-number-changed-after-update.html
Mystery solved? (thank you again so much Yingtong)
I guess it never really bothered me since I always had W7 (which never saw a substantial update since SP1 a decade ago). 

> Doing some more digging. If Steam.exe is not running, the app will not run, regardless of you setting these environment variables or the app id trick. It seems in this case, it looks up the parent dirs for Steam.exe, like you described in the other thread.

I also realized I had been missing the most stupid of fixes. 
https://www.pcgamingwiki.com/wiki/User:Cyanic/Steam_DRM#Common_error_codes

**Comment by mirh** [comment]
This is sad..
