### ISSUE TITLE
ME1/2 DLC Prompt for Steam Users

### ISSUE THREAD

**Issue by Herobrine24** [ME3Tweaks/ME3TweaksModManager#193]
Since ME1 and ME2 on Steam don't come with all the DLC, I thought it would be a good idea to show a prompt to users that have those games on Steam with a link to https://help.ea.com/en-us/help/faq/dlc-for-classic-games/#masseffect so that they can download and install these DLC, which they might need for certain mods anyway.

**Comment by mirh** [comment]
Putting aside that mods shouldn't have extra hard dependencies imo, most ME2 dlcs are to be paid though. 
Maybe it could even make sense for ME1, but it should be pretty unobtrusive.

**Comment by Mgamerz** [comment]
Mods regularly have dependencies. Users are warned of missing dlc when they
try to make a backup.

**Comment by mirh** [comment]
If you are modding the cittadel DLC, of course you should depend on it. 
If you are ALOT on the other hand, I don't think it would be reasonable to require all DLCs (except perhaps for ME1 for the usual reason I already explained.. though I once read people hard bent on hating pinnacle station and not wanting to install it)

Btw (now that I think to it but completely OT) ME1recalibrated should recommend the `m_bIgnoreDLCRequirements` trick as a workaround to "save locking".

**Comment by Mgamerz** [comment]
ME1Recalibrated does not write itself into your save files. It hasn't for over a year now.

**Comment by mirh** [comment]
I know, though they still have that "if you have an old save, sorry it happened and RIP" warning on the main page. But you can actually fix it.

**Comment by mirh** [comment]
On the other hand, now that I think to it.. It you have steam/retail it really wouldn't hurt to have some kind of automatic handling of [this clusterfuck](https://www.pcgamingwiki.com/wiki/Mass_Effect_2#DLC_and_expansion_packs).
But I'm skeptical such convenience feature should belong to mod manager.

**Comment by Mgamerz** [comment]
I was thinking about this recently. I don't think it really belongs as a 'first class feature' in mod manager but it would be interesting to see what silent options the installers have. Might be able to produce a script or something to just automate whatever dlc the user has. Though could just be easily an external program (drag your dlc downloads folder onto this ui, etc)

**Comment by mirh** [comment]
The installers should be all fairly normal NSIS 2.34 plus rar (funnily enough rebranded as "BioWare Installer 1.03").

**Comment by mirh** [comment]
Ehrm... I think we may be actually having a worse problem here
https://steamcommunity.com/app/17460/discussions/0/3112519935866909355/

**Comment by mirh** [comment]
I think it should be pretty easy with 7z to bypass the installers altogether, and just unpack the content in the game folder. 
The only complication is that in ME1 you have to remember to write the two *ergc* keys (AWKKMJLSKFUEZSJJZ8NQ and 5GUCXRFPQNBMTJBD3L5J are the official ones I believe), and perhaps auto-detect which Pinnacle Station language to download.

**Comment by mirh** [comment]
Or as an added safety layer, we could even figure out what the [cdk_268417995](https://steamcommunity.com/app/17460/discussions/0/3113647550058638261/#c3110270484064676766) format/hash is made (and then restarting the steam client after writing it)
