### ISSUE TITLE
Detect (V)RAM size and select proper texture settings

### ISSUE THREAD

**Issue by mirh** [ME3Tweaks/ME3TweaksModManager#209]
I have seen many people recommending or installing ALOT, not just (or not even at all) because they wanted a nicer looking game, but because of its perceived "fixing bugs" nature. 
(which it has of course, but clearly you shouldn't cut your steak with scissors if I can explain). 
And I have come to read of several people with a 2010-equivalent computer that of course isn't really the bestest hardware on the shed to run 4K textures. 

And the same time I was also told that insofar as LOD size is kept at its original settings, the mods (well with the exception of improved static lighting perhaps) should perform just the same of the vanilla game. 

So I was wondering if we couldn't also spoon-feed the users about this (not sure against which component I should have opened this feature request against), to save them from bad framerate. 
Or alternatively, it would be dope if we could have an asi mod that adds higher settings than "ultra-high" in-game (so anybody can select what they want), but I don't know how much feasible it could be.

**Comment by mirh** [comment]
> Alot installed at vanilla lods still had some improvement (but not much)

Uh, right. Because not all vanilla textures were maxing out the original LOD limits. 

Well, anyway, I guess this feature should exist in the tweak manager then.

**Comment by Mgamerz** [comment]
I'm closing this because I don't think it's worth the effort to implement and support at this point in time.

**Comment by mirh** [comment]
Then just leave it open..
Or if you meant that you don't care about OT anymore, well, technically speaking this doesn't just apply to it (it was about hardware and noob users eventually, not software)
Even if LE may not have any meaningful inherent memory limitation, even the recommended requirement of 4GB of VRAM probably isn't going to be enough if somebody wanted to plaster the game with 4K textures (or whatever was the new remastered limit).

**Comment by Mgamerz** [comment]
We don't change LOD settings in LE. And this is my repo, I will close issues that I am not going to be pursuing.
