### ISSUE TITLE
ME1 DLC Mod Starter Kit generates Autoload.ini with incorrect text encoding

### ISSUE THREAD

**Issue by henbagle** [ME3Tweaks/ME3TweaksModManager#211]
When creating a new DLC Mod for Mass Effect 1 via the starter kit option, the Autoload.ini file is created with a UTF-8-BOM text encoding, instead of a UTF-8 encoding. This appears to stop things like GlobalTlk files from being loaded into the game.

I messed around with the Autoload.ini a bunch and a UTF-8-BOM encoding will cause the game to not load the GlobalTlk file (shown in the console with obj linkers). My guess is that other files specified in Autoload will also not get loaded. Re-encoding the Ini file with UTF-8 solves this problem. Other files in the mod still get loaded either way.

Let me know if this is the appropriate place for this issue, or if this is actually a problem with the Mod Enabler ASI, or something else.

**Comment by Mgamerz** [comment]
Thanks for the detailed info. I know ME2 ini files are BOM specific but I probably did not include code for ME1. Do you have a sample project/mod that has text changes so I can verify it works after generating it?

**Comment by henbagle** [comment]
I do but I can't seem to upload it here. I'll try to PM it to you on Discord. obj linkers in the console will also show you which GlobalTlk files are loaded.

**Comment by Mgamerz** [comment]
This has been fixed in the 6.2.1 release, which is about to finish soak testing. Thanks for reporting it.
