### ISSUE TITLE
Document more values in MEIM (feat extra data-mining)

### ISSUE THREAD

**Issue by mirh** [ME3Tweaks/ME3TweaksModManager#212]
While I was [smashing my head](https://github.com/ME3Tweaks/ME3TweaksModManager/issues/173#issuecomment-782988254) against the ways of the ~~lord~~ localization, I noticed DefaultXYZ.inis have a helluva of comments. 
DefaultGame.ini in particular has almost half of the classes commented. 

***On top of that*** while scavenging the net left and right for translations (did you know turkish, korean, poroguese and maybe also japanese exist?) I [found out](https://web.archive.org/web/20090831234252/http://meforums.bioware.com/viewtopic.html?topic=691350&forum=125#6616001) that [previous](https://www.fileplanet.com/archive/p-54982/Mass-Effect-v1-01a-Patch) to patch 1.02, DefaultEngine.ini used to have right-off-engineers-mouths remarks going all the way back into 2005. 
...
Carried away by the discoveries, I also went at great lengths to check the xbox and pc rtm isos... to no avail of extra info, but this is already quite much. 

p.s. not saying `bDisablePhysXHardwareSupport` does absolutely nothing but if it works at all only AGEIA ppus [should](https://forums.guru3d.com/threads/mass-effect-2-gpu-physx.315002/#post-3485180) be [supported](https://web.archive.org/web/20150324215444/http://physxinfo.com/wiki/Category:Games_without_hardware_acceleration)
p.p.s. when did `MaxSmoothedFrameRate` started to be a concern in <ME3 ?
p.p.p.s. now that I think to it, editing a ridiculously well-streamlined XML file is so easy that I could in fact contribute this myself, but after 4 days of efforts I'm quite tired for the moment.

**Comment by Mgamerz** [comment]
I am closing this as MEIM is not going to be further developed.
