### ISSUE TITLE
Launch Parameter Menu

### ISSUE THREAD

**Issue by Herobrine24** [ME3Tweaks/ME3TweaksModManager#217]
Add an arrow button to the side of the Start Game Button which opens a drop-down list with the option "Launch Parameters". The Launch Parameter Menu would display all launch parameters that are known in the same style as the ASI Mod Manager where you just tick the boxes of the parameters that you want the game to launch with.

**Comment by Mgamerz** [comment]
What kind of launch parameters?

**Comment by Herobrine24** [comment]
> What kind of launch parameters?

I only know of -nomoviestartup....

**Comment by Mgamerz** [comment]
That option is not that relevant these days, as it seems to have been fixed by the Kasumi Crash Fix ASI.

**Comment by Herobrine24** [comment]
> That option is not that relevant these days, as it seems to have been fixed by the Kasumi Crash Fix ASI.

yeah but when testing mods for ME2 it would be great if you didnt have to wait for the loading screens and intro videos all the time

**Comment by Mgamerz** [comment]
This has been implemented into beta builds. 

Currently I am working on expanding its functionality to allow saving profiles as well as supporting custom command line arguments.

**Comment by Mgamerz** [comment]
This is now available on stable 8.0.1.

**Comment by mirh** [comment]
FWIW you can still use [origin](https://www.dm.origin.com/download) 
(as for avoiding the videos, I would guess renaming the files still works in that regard)
