### ISSUE TITLE
string_deploy

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#22]
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/50d3327f5894c9df31b40e64e59d71e373c11405/MassEffectModManagerCore/modmanager/localizations/int.xaml#L262

While I get the meaning, I'm having trouble translating it, which makes me wonder if that's the correct term in the first place.

Alternatives that come to mind:
- export: imprecise, you could also export an existing mod from the library
- pack/package: maybe, and more so if the same terminology was used for importing mods
- ?

**Comment by Mgamerz** [comment]
Deploy = Take mod and package it into a 7z file. However it is more than just turning into a 7z file as I package it a certain way. Package I suppose could work too. This term is only shown in developer mode so I assume the end-user in this case will have at least some idea of these terms.

**Comment by HarHarLinks** [comment]
To me deploy seems to imply a little more than just packaging it the mod manager way, namely including some kind of publishing. But as I understand it, you still have to manually upload, publish and distribute the package.

**Comment by Mgamerz** [comment]
string_deploy is used in this context:

![image](https://user-images.githubusercontent.com/2738836/70675982-f3fe3380-1c47-11ea-90d1-f39e4fad5a7a.png)

![image](https://user-images.githubusercontent.com/2738836/70675994-fa8cab00-1c47-11ea-876b-a72a796e79c9.png)

The title of the dialog says prepare for distribution. I guess it could be a bit more clear, however when "deployment" is done, windows explorer pops up and shows the mod. As this is a feature only available in developer mode, I think this would probably be for the more technically inclined, and it should be a reasonable expectation that that the mod isn't being uploaded anymore (e.g. Deploy to NexusMods). Maybe if it was changed to Deploy to .7z?

**Comment by HarHarLinks** [comment]
I think it's fine in English. Package could still work, too.
There's no fitting literal translation to German, which is why my best bet is "packen" (package).

**Comment by Mgamerz** [comment]
This does not have to be a 1:1 literal translation. Convert it to a way that makes sense in your language, just make sure it still makes sense. Though make sure you ask on technical stuff.

**Comment by Mgamerz** [comment]
This string was changed to `Deploy to .7z`.
