### ISSUE TITLE
Suggestion: ModDesc editor - delete added AltDLC/AltFiles

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/ME3TweaksModManager#236]
Currently there is no way to delete an optional entry of alternate dlc or files if you have created something by mistake.  This can be problematic especially if you have to fill out all the verified info before saving.  You can lose all your edits.

**Comment by Mgamerz** [comment]
This has been implemented into the M3Core branch. Whenever the next beta build is released it'll be there. Though you can't serialize anything without it using moddesc 8 which will not be supported for production use until that hits stable.
