### ISSUE TITLE
Legendary Edition options only visible if Original Trilogy generation is selected

### ISSUE THREAD

**Issue by d00telemental** [ME3Tweaks/ME3TweaksModManager#243]
On 7.0.2 BETA (Build 120). I assume that the issue is in these lines:

https://github.com/ME3Tweaks/ME3TweaksModManager/blob/65cddc2bb3ff62175d247d469ad45a099c510b2b/MassEffectModManagerCore/modmanager/usercontrols/OptionsPanel.xaml#L222

https://github.com/ME3Tweaks/ME3TweaksModManager/blob/65cddc2bb3ff62175d247d469ad45a099c510b2b/MassEffectModManagerCore/modmanager/usercontrols/OptionsPanel.xaml#L232

https://github.com/ME3Tweaks/ME3TweaksModManager/blob/65cddc2bb3ff62175d247d469ad45a099c510b2b/MassEffectModManagerCore/modmanager/usercontrols/OptionsPanel.xaml#L239

**Comment by Mgamerz** [comment]
Thanks. This was fixed in  this commit: https://github.com/ME3Tweaks/ME3TweaksModManager/commit/8a8c7e54b4c5721d5a056fe2c1694dced3416545 and will be available in the next build.
