### ISSUE TITLE
.NET 6 and Legendary Explorer downloader [not whole program]

### ISSUE THREAD

**Issue by Lubieerror** [ME3Tweaks/ME3TweaksModManager#252]
**[Version]**
_7.0.3, Build 121_ and _origin/master_

**[System]**
Windows 10 Pro x64
**[.NET installed]**
_.NET Framework 4.8_
SDK: _.NET Core 3.1.411_ Runtime: _3.1.17_
SDK: _.NET 5.0.302_ Runtime: _5.0.8_
SDK: _.NET 6.0.100-preview.6.21355.2_ Runtime: _6.0.0-preview.6.21352.12_ (from Microsoft.NETCore.App value)

**[Problem]**
While Legendary Explorer run totally fine on machine with .NET 6 installed (tested with version from git), I wasn't able to download it through M3TMM [Tools > Additional modding tools] with error **".NET 5 not installed"**.
![image](https://user-images.githubusercontent.com/11427815/126871826-ee8e4393-9bcb-445a-8e26-b9605d922f0c.png)

**[Possible cause]**
The fault lays on _IsNetTuntimeInstalled_ from [MassEffectModManagerCore/modmanager/Utilities.cs](https://github.com/ME3Tweaks/ME3TweaksModManager/blob/aa269d5ab0e85f14eecf774172a43384e64b2cd4/MassEffectModManagerCore/modmanager/Utilities.cs#L82). In theory the check should also allow more recent (and future) versions, (`netVersion > new Version($"{minVer}.0.0.0")`) but TryParse fails to parse preview:
![image](https://user-images.githubusercontent.com/11427815/126871704-24c75fdf-f9d7-4cdf-9f2b-e0ad14ef9f05.png)
(Thanks Microsoft 🙄)

I should upload one of possible solutions as PR soon.

**Comment by Mgamerz** [comment]
I merged this, thanks for the PR. I think if you're installing preview versions of .NET you will hopefully know what you're doing.
