### ISSUE TITLE
Suggestion: Portable instance of Mod Manager

### ISSUE THREAD

**Issue by Patchier** [ME3Tweaks/ME3TweaksModManager#267]
Exactly what it says on the tin. I'd rather have a pre-extracted zip as opposed to an exe.

**Comment by Mgamerz** [comment]
If you have 7zip installed you can right click the exe and extract it. It's literally a 7z file with a n executable header for the extractor inserted before it.

I don't offer zip downloads cause users in the past would just put it wherever - temp directory, game directory, and I wasted a lot of time with users who couldn't read the directions on where it goes. So I switched to an SFX.
