### ISSUE TITLE
Feature Request: Display Warning if SFXGame/Startup was merge modded and youre about to install a mod that has to ship the full file

### ISSUE THREAD

**Issue by Herobrine24** [ME3Tweaks/ME3TweaksModManager#273]
Add a warning that tells users to install SFXGame/Startup shipping mods first and any merge mods last when mod manager detects that such a mod is being installed and the basegame files were modified.

Example warning:
![Untitled](https://user-images.githubusercontent.com/73685731/143766421-37cd4613-5239-4c21-bacf-76d36a16a1d7.png)

**Comment by Mgamerz** [comment]
I'm thinking of implementing this, but instead it will be a deployment check. Could still do end-user ones I suppose but the user doesn't really have any recourse if they press install anyways unless they can remember what they installed (since the dialog will go away right afterwards).

**Comment by Mgamerz** [comment]
This is implemented as a deployment check in Mod Manager 8.
