### ISSUE TITLE
Not applicable options on Option groups can be selected on 7.0.6

### ISSUE THREAD

**Issue by mkhaar** [ME3Tweaks/ME3TweaksModManager#278]
The new UI for option groups allows selecting options that are marked as not applicable (such as those requiring a missing DLC/MOD, for example). Despite the red message appearing, they can be selected and the mod can be installed with options that are not supposed to.

This didn't happen with the previous version of the option groups menu, in which those marked as "not applicable" were greyed out and the dot was unselectable.

**Comment by mkhaar** [comment]
24th January build still shows this problem; with non-applicable options from an option group being able to be selected to install and installing themselves to the mod target folder despite lacking the requirements.

**Comment by Mgamerz** [comment]
Looked at this today, I am going to have to probably overhaul the entire alternate selection UI, as the way it is currently done was kind of a prototype, and unfortunately doesn't have any real way to disable item selection.

**Comment by Mgamerz** [comment]
Going to close this as it's part of 8.0, which is going to get another rework, and this won't really apply to that implementation.
