### ISSUE TITLE
Option to bulk import mods

### ISSUE THREAD

**Issue by GreatBarrier86** [ME3Tweaks/ME3TweaksModManager#280]
It doesn't appear that the mod manager supports bulk applying of mods. Considering that applying things like ALOT requires resetting the entire game directory, then applying the mods again, then applying the graphics, it would be helpful to have an option to enumerate through all the mods and apply each of them, either with default settings or pop the settings dialog for each. I can explain better in pseudo code. 

Is that of interest to anyone?

Something to the effect of:
```
foreach (var mod in mods)
{
    if (GlobalVariables.BulkImportUsingDefaultSettings || mod.ShowOptionsDialog() == DialogResult.OK)
   {
       Import(mod);       
   }
}
```

**Comment by Mgamerz** [comment]
This is done with Batch Mod Installer. I plan to implement a batch file drop system but haven't worked on that yet.

**Comment by GreatBarrier86** [comment]
Lord.  I didnt notice that. Thank you.

**Comment by Mgamerz** [comment]
I'm closing this in favor of #285, since it will encompass this via drag and drop.
