### ISSUE TITLE
Feature: Starter kit 'kits'

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/ME3TweaksModManager#286]
Some things that could be useful for mod developers is the idea of a starter kit 'kit', like an option set to help jumpstart a mod.

For example:
- [x] Squadmate outfit merge kit: You'd select a squadmate and it could generate a blank, working version for a single squadmate, with items renamed to match the DLC foldername. The developer would then just change the mesh, materials, and the squadmate images.
- [x] Startup file: Automatically generate a blank startup file that is already defined in the coalesced

This would take a significant engineering effort (lots of LEC code) but would probably make these features more widely used.

Mod Manager may need to have a feature where it allows a blank mod to load and/or blank mergemods. ME3CMM had this in it's code for when ModMaker mods were being compiled and a new mod was generated; this may help with issues such as generating a blank merge mod. These blank options would block deployment AND importing (so users don't try to just zip the folder).

**Comment by henbagle** [comment]
Plot Manager and 2DA files for game 1 would also be a great part of this feature

**Comment by Mgamerz** [comment]
Here's a mockup. The backing code for these checkboxes would be a method that operates on a DLC folder. So starter kit would generate the mod and then each checked option would run. This will also allow code recycling to right click a mod to run that option on the mod, such as adding an existing startup file, which is something already coded up in one of my current projects, with a full proxy interface for coalesced, regardless of which game you are working with.

![image](https://user-images.githubusercontent.com/2738836/184523491-973ee516-550d-4187-b2be-df99992eebff.png)

**Comment by Mgamerz** [comment]
This is now available on stable 8.0.1, and will probably be expanded on in the future.
