### ISSUE TITLE
static files

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#29]
"Mod Manager components" is more descriptive and relevant than just "files".
Here you use "supporting files":

https://github.com/ME3Tweaks/ME3TweaksModManager/blob/57b730b41b36d2a7cbc6e0193111fa4d18de990d/MassEffectModManagerCore/modmanager/localizations/int.xaml#L149

Out of curiosity, which ones are the static files anyway? Got to do with "content updates"?

**Comment by Mgamerz** [comment]
Static files are items that aren't going to change, so I don't include them in the main download, as updates to Mod Manager download the whole package. Things like the object info databases, which together add like 1-2MB even compressed, likely aren't going to change so I only download them once mod manager is setting itself up the first time. "Static" in the idea that they don't change.

**Comment by HarHarLinks** [comment]
i think in cases like this (more often actions like checking, downloading, updating), it also needs to be very clear whether content/files/components refer to M3 or Mods.
