### ISSUE TITLE
Tooltips broken when minimizing 

### ISSUE THREAD

**Issue by Masamune3210** [ME3Tweaks/ME3TweaksModManager#295]
Every time I minimize the Manager, the tooltip for the "Play Game" button will appear in the top left corner of the 1st monitor until either I unminimize the Manager or the timeout for the tooltip fires.

Version 7.0.6 Build 124
![image](https://user-images.githubusercontent.com/1053504/161368915-2453f445-7302-48ba-acd2-9c88e2b1d64a.png)

**Comment by Mgamerz** [comment]
Hi, sorry for months long reply. I'm aware of this issue (I've had it many times). My original fix years ago was to make it have 20s tooltip timeout. However, I am now more aware of specific tooltip methods I can use to hide all tooltips on minimize, which I will implement in the next build.

**Comment by Mgamerz** [comment]
Are you able to reproduce this on 8.0? I have since changed to .NET 6 and they changed a bunch of stuff related to tooltips and I'm having trouble reliably reproducing this like I was before.
