### ISSUE TITLE
New feature request: Delete Batch Installer Mod lists

### ISSUE THREAD

**Issue by mkhaar** [ME3Tweaks/ME3TweaksModManager#296]
Either I am blind or currently there is no way to delete, only edit/repurpose created Batch Installer Mod lists. I think it would be a good feature to have, especially if we start making more and more people aware of the perks of using this system.

**Comment by Mgamerz** [comment]
This (I think) is implemented in the current 8.0 beta. I'm going to leave it open though until that ships.
