### ISSUE TITLE
content updates

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#30]
>Content is just online updates. Such as refreshing latest items (tips, importing info, etc).

only used once, the other times "content" is used is to do with required DLC/Mods:
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/57b730b41b36d2a7cbc6e0193111fa4d18de990d/MassEffectModManagerCore/modmanager/localizations/int.xaml#L24

1. why does this need an update button that's so prominent?
1. also surely you fetch it automatically anyway, is this more than a debug option? if yes, user needs clearer name
1. is there really no better name than content? supporting files, #29?

**Comment by Mgamerz** [comment]
1. If I am fixing something on server for a user there needs to be a button for forcing refresh
2. This is automatically downloaded but I throttle it to no more than once a day on automatic mode
3. It's a bunch of things. In ME3CMM it's always been labeled as content. It includes tips service (tips on right panel), third party mod identification and importing information, checks for mod updates to all mods, etc. It's essentially the startup of Mod Manager excluding the mod manager update check for itself.

**Comment by HarHarLinks** [comment]
So basically M3 = M3.exe + "static ~~files~~components" + content?
Content could by dynamic components, or another better fitting synonym?
Another idea: M3 databases, as these are essentially databases for a bunch of strings.

**Comment by Mgamerz** [comment]
These are definitely not databases. Some content is things like the 7z dll.
