### ISSUE TITLE
"Key value"

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#308]
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/f4155d20cf746b317a87b3e26e9509cd6ab32fd2/MassEffectModManagerCore/modmanager/localizations/int.xaml#L1276-L1277

"Key value" sounds wrong or at least too ambiguous to me. It's either key, or value. Or a key-value pair.

**Comment by Mgamerz** [comment]
In this case, it should probably be `'OptionKey' value`. This error message is when an alternate references itself as a dependency when checking it's `OptionKey`, so the value of `OptionKey` is invalid. I'll change it to `OptionKey`.

**Comment by Mgamerz** [comment]
Actually I'm going to change it to this:
`    <system:String x:Key="string_validation_alt_dependsSelfReference">Alternate {0} references its own 'OptionKey' in its DependsOnKeys list, which is not supported. Invalid value: {1}</system:String>
`

**Comment by HarHarLinks** [comment]
Will you notify localizers about this change? Will the localization tool be able to mark this diff? Will it wait for the next version?

**Comment by Mgamerz** [comment]
Localization tool will not mark it as a diff since this is the same build still. I will just tell localizers the string changed.
