### ISSUE TITLE
ME1 Ini Modder vs. merging multiple Ini Mods manually

### ISSUE THREAD

**Issue by zipacna** [ME3Tweaks/ME3TweaksModManager#318]
Hope this request fits here, or should I rather ask on the general modding channel?

As I am currently preparing a playthrough (round 16 or so, lost count around the dozen) of **OT ME1**, I (veteran player, intermed. mod user / software dev, novice modder) am looking into some **Ini Mods** ([265 - Inventory](https://www.nexusmods.com/masseffect/mods/265) and [132 - Play as Asari](https://www.nexusmods.com/masseffect/mods/132), [173 - Dialogue Wheel with Keyboard](https://www.nexusmods.com/masseffect/mods/173), [96 - Gameplay Overhaul](https://www.nexusmods.com/masseffect/mods/96), [87 - ME1 Gameplay Tweaks](https://www.nexusmods.com/masseffect/mods/87), etc.). Their consensus - insert fitting geth joke here - seems to be to modify the respective `Documents/BioWare/Config/BIO*.ini` files and then setting them as read-only.

I was wondering, from where the Game generates those. I have found some candidate in `Origin Games/Mass Effect/BioGame/Config/Default*.ini` files but from what I have learned in my last modding session (thanks to 55tumbl for enduring me) of *ME LE* the `Engine.pcc` (or here the `engine.u`) seems to be tied in as well (or am I wrong?). The `Default*.ini` files seem to have slighty different values than the `Bio*.ini` files (mostly formatting like comments or order of sections). Could be misleading though (transferred my Documents folder from my old hard-drive).

What I am trying to achieve would be "merging" multiple standalone Ini Mods (see Ids from Nexus above) which do not lock the configuration (read-only) and ideally would be deployable with ME3Tweaks (have failed at creating an LE merge mod regarding Bio 2DA tables). I am aware of the **Mass Effect Ini Modder**, but it only seems to cover my use case partially. Increase Inventory Size (yes), add another Character Model (partially) and modifying anything other than BioEngine, BioGame, BioParty (no, e.g. BioInput).

If it would need changes to the Module of ME3Tweaks housing the ME Ini Modder, I could offer a Pull Request, given some introduction/docs to the "Marvel of Engineering-Tool-Chain" ME3Tweaks appears to be. Any pointers are appreciated (ideally hyperlinks and not *void). I have some knowledge of WPF and MvvM but lack the (ME3Tweaks)-domain-specific perspective.

Have been using ME3Tweaks v7.0.6, not sure what is planed for v8. Without diving to deep into the rabbit hole, I have looked at the github repo briefly, the v8 changelog does not seem to include anything about the ini modder. The existing [ME1IniModder.xaml.cs](https://github.com/ME3Tweaks/ME3TweaksModManager/blob/master/MassEffectModManagerCore/modmanager/windows/ME1IniModder.xaml.cs) only seems to support BioEngine, BioGame, BioParty to a certain degree.

**Comment by Mgamerz** [comment]
The default ini files are used when the bio*.ini files need generated (or regenerated). The game's changes are then layered on top.

**Comment by zipacna** [comment]
As I am currently preparing an OT playthrough, I will try to modify the Default*.ini files to see if I can leverage the vanilla mechanism into using any ini mods as the baseline and let the game generate the Bio*.ini files from that. Once I get that working I might look into the ini modder folder and try to integrate it. For now, I will try to keep things simple. Just for reference, this: [https://github.com/ME3Tweaks/ME3TweaksModManager/tree/master/MassEffectModManagerCore/modmanager/meim](https://github.com/ME3Tweaks/ME3TweaksModManager/tree/master/MassEffectModManagerCore/modmanager/meim) is the correct folder? If so, the issue can be closed for now.

**Comment by Mgamerz** [comment]
Yes meim is the folder with the code for mass effect ini modder.
