### ISSUE TITLE
verify correctness

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#32]
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/57b730b41b36d2a7cbc6e0193111fa4d18de990d/MassEffectModManagerCore/modmanager/localizations/int.xaml#L273

"Verifying correctness", both have the same meaning. A Hendiadys or similar linguistical construct.

**Comment by HarHarLinks** [comment]
same issue:
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/50d3327f5894c9df31b40e64e59d71e373c11405/MassEffectModManagerCore/modmanager/localizations/int.xaml#L270

**Comment by Mgamerz** [comment]
I am going to be going back to fix these manually, as there is an issue with a trailing space in XML that I was not aware of until after the first localizations were input. I'm going to do it manually after everything is finished.

**Comment by HarHarLinks** [comment]
In my language "verify" means "make sure [...] is correct". I thought English was the same.

It's not really big of an issue, but as I'm looking at these anyway I'll mention everything catching my eye.

**Comment by Mgamerz** [comment]
That is what the string is meant to imply. You, the mod developer, need to manually look at the version, and determine if it is correct.

**Comment by HarHarLinks** [comment]
I think it's what I meant. If you want to keep it for clarity, we're good.
