### ISSUE TITLE
Mod Manager 8.0.1 PRERELEASE (Build 127) won't skip MELE Launcher if using EA App

### ISSUE THREAD

**Issue by mkhaar** [ME3Tweaks/ME3TweaksModManager#324]
Decided to give it a go to the EA App which will be replacing the Origin platform at the end of the year to test different modding frameworks.

Currently, in Stable and Beta versions of the Mod Manager, launching any MELE game through it would skip the launcher if using Origin (can't test Steam behavior myself, so I do not know if that was the case as well or not). If updating to the EA App, which replaces Origin, the Start Game button on the stated Mod Manager build will no longer launch directly any of the Legendary Edition games, but instead take you to the MELE Launcher. This has been tested with trying to launch all 3 MELE games, and all 3 triggering the launcher.

Not a priority issue, but thought to raise this, since people are already getting the prompt to update and, in a few months, the update will be forced.

**Comment by Mgamerz** [comment]
This should be fixed in the latest beta.

**Comment by mkhaar** [comment]
I just noticed the label on the issue. I think it is definitely solved; however I don't actively keep testing with the EA App... I can close it if you prefer it?

**Comment by Mgamerz** [comment]
I keep issues open until a stable version that fixes them is released.

**Comment by Mgamerz** [comment]
This is now available on stable 8.0.1.
