### ISSUE TITLE
(Pipe-Dream of a) Specification Draft for a new Major Version of ME3Tweaks Mod Manager (e.g. v9.0 or v10.0)

### ISSUE THREAD

**Issue by zipacna** [ME3Tweaks/ME3TweaksModManager#327]
*cue to call me crazy*

## Preface

**What I would like to achieve with this Specification (Draft):** (minecraft-like) Mod Packs as an extension of the (ME3Tweaks Mod Manager - personal abbrev. M3T) "Mod Management -> Batch Mod Installer";

**Where (the hell) I am coming from:**
- I am hugely influenced by my Experience (since 2011) with the Minecraft Modding/Plugin Ecosystem
- and have a background (since 2017) in Business Information Systems (basically Computer Science / Software Engineering), working as a "Software Engineer" (Software Developer by Title but Engineer by Law), so C#/Python/etc. whatever works best.
- Additionally I have rough/intermediary Mass Effect Modding Experience; more than a dozen playthroughs of the Trilogy with various degrees of DLCs/Mods (since 2014); did some splash/coalesced edits, pcc edits, bundled them as M3T Mod (unpublished) and applied hundreds of mods by others with the *M3T* Toolchain to various installations of OT/LE. Been a few times (irregularly) on the Tweaks Discord as well.

**My Motivation/Goal:**

From that I have arrived at the conclusion, that going from playing the Game (for the first time to a couple of times) -- adding the first Mods, adding *more*, to customizing "accessable" Mods (understandable with rudimentary Knowledge), to writing ones own Mods from e.g. Config or Visuals only to combined Mods (e.g. pcc+mem) -- to expert-level Modder (with Toolchain Involvement), needs A LOT (pun `    ` indented) of **Time**, which can be discouraging/frustrating but could also offer a Personal Career Path (or at least a Hobby), when those skills aquired from modding are applied to another Area of Interest.

My understanding of the **Philosophy of the Mass Effect Modding Ecosystem and specifically ME3Tweaks Mod Manager** is to allow players to have more fun (better Toolchain = better/more Mods) and Modders to be empowered to deliver just that. To which my Proposal could contribute (at least I hope so).

*cue to call me crazy*

### Workflow
Role naming-reference:
- **M3T** (ME3Tweaks Mod Manager)
- **Modpack Creator** (Programmer / experienced Modder)
- **Enduser** (Non-Programmer or Newbie Modder/ME-Player)

How my Proposal turns out (pipe-dream vs. precursor to a better system vs. partial or full implementation) depends mostly on Time and Motivation (of anyone involved) and primarily the authorization of the Author(s) of M3T.

**Workflow-Ideas**:
1. Modpack Creation (*Modpack Creator*) aggregates Mods
    1. Checks Licenses; maybe default Approach would be contact via Nexus/Discord, if not reached after 30 days -> assume fair use / attribution (unless stated otherwise).
    2. Handles machine-readable Compatibility of the Modpack via Modpack Manifest (packdesc.ini? json? ron? yaml?); for having some starting point a "database" of some sort would be needed (see 2. Machine-Readable Compatibility).
2. Machine-Readable Compatibility (*M3T* or independent Service) via Modpack Manifest
    1. Crawl Nexus for updates / machine-readable information (maybe once a day).
    2. Personal Manual Labor of me and/or others checking every ME1/ME2/ME3/LE mod page on nexus to translate the prosa / text-form described dependencies/compatibilities of ALL mods into a machine-readable Format.
        - I am aware of the needed time, the initial first round could be roughly 5 hours per week over 3 months for a single person alone (assuming 3000 mods in total and only 1 minute per mod on average).
        - Crawled Information could reduce the manual labor to only the "relevant"/remaining mods or *M3T* could advise people creating mods to provide the compatibility information themself (they probably know it the best anyway).
    3. Some form of Hosting/Syncing Service would be needed (could this be provided through existing *M3T*/ALOT infrastructure?). This would allow for crowd-sourced decentralized/asynchronous creation and maintainance of the Compatibility Information.
3. Modpack Distribution (*M3T*)
    1. Distribution like the [M3T Mod Maker](https://me3tweaks.com/modmaker/)? For me the description of the Mod Maker (on the liked page) is a bit ambiguous, is the Mod Maker only Multiplayer Mods?
    2. Once a Enduser selects a Modpack through either *M3T* (browse available modpacks from inside *M3T*?) or by importing a downloaded zipfile (Modpack Manifest only, no mods themselves) into M3T, it should perform the usual vanilla check for the respective game, resolve the dependencies by the Modpack Manifest and download the specific version of the listed mods from Nexus. As the downloads could be rather large and through the rate-limits of Nexus rather time-consuming, maybe allow for scheduled downloads or bulk-downloads over night.
    3. The Modpack Manifest itself could be rather small, as it would only need to include the (parsable) instructions (similar to moddesc.ini) and dependencies (game + mod ids to download)
4. Modpack Use (*Enduser*)
    1. *M3T* Wizard asks *Enduser* IN ADVANCE for configuration selection (Options like which Outfit, which Shieldgate% etc.)
    2. *M3T* Wizard asks *Enduser* for ALOT/ALOV preferences (can any mem file be packaged in a *M3T* mod?)
        - Otherwise apply ALOT, then invoke MEM? My thought here is to allow Modpacks to cover all layers of Mods (from Vanilla to *M3T* to manual pcc/coalesced Edits across ALOT to manual tpf/mem Edits).
        - I am aware of the limitations regarding Order/Pointers between M3T and ALOT mods, so this would be a one-way operation.
        - But if the Modpack is configured properly, this would allow for a one-click Installation from the *Enduser*, once they selected (ideally UX-friendly) their Configuration Preferences.
    3. *M3T* Wizard performs "preflight"-Checks; before each Step/Layer and asks User to confirm Order / allow Change on Failure (similar to my Smaller Alternative Ideas for the ALOT Installer, see below)
    4. *M3T* Wizard applies *M3T* mods (with selected Config), triggers ALOT (with selected Config?) and afterwards uses ALOT/MEM to apply any dds/tpf/mod(convert to mem?) preferences
        - Some ALOT Questions (my current understanding of post-ALOT modding is limited): Are Mesh Edits (.mod?) only recommended / effective before applying ALOT itself? What tools / steps to use to get from dds to mem and back?
        - Ideally have Backups along the entire Modpack Installation Process, e.g. only changes Files per Step/Layer by Checksum in simplified "Commits" as Snapshots
        - Maybe have some Hard Drive Space Availability Helper (looking at my 2TB of various Mass Effect Installations, Backups and Mod Downloads/Staging); the Modpack Manifest could even contain an estimate, based on selected Game (Vanilla Size times 3 for Backups) + Total Amount of Nexus-listed File Sizes of all included mods.

*cue to call me crazy* (a bunch of times, from the huge block of brain dump above) *cue to call me crazy* *cue to call me crazy*

### Smaller Alternative (Update to the ALOT Installer)
In case the Proposal above is too much / to abstract for now (more like a strategic pursuit), I have some smaller Request regarding the ALOT Installer (or would that be better as a Issue on another Repository?).

Update-Ideas (primarily for free-mode or, if it fits, the others as well):
1. Allow to sort / group the File List (maybe even by drag & drop); What exactly are the Manifest Files described in the Import Assistent? Do they already cover my Update-Ideas? If so feel free to RTFM me (with a proper link) or maybe include a Tutorial in the ALOT Installer?
2. Enable/Disable Groups/Single Entries (currently a bit cumbersome for single entries in my opinion)
3. Allow to clear the File List (or a Group); as I currently only know to do that by closing and reopening the ALOT Installer

*cue to call me crazy*

## Collaboration Offer
If any of those Ideas are considerable I would be happy to contribute anything (be it Time, Money, Specifications, Designs/Mockups or actual Software Artifacts). The Timescale is probably at least over the span of a year.

I will try to add some Pictures over time to ease Discussion (if it is not outright shutdown).

One Process Model (of how to implement the Proposal to some Degree) could be:
1. to discuss the Proposal in this GitHub Issue or the Tweaks Discord. Either remotely/asynchronously or even via synchronous VOIP for closer Collaboration (depends on timezones, personal preferences, etc.)
2. escalate to creating Designs/Mockups
3. escalate to Minimum Working Examples for some Aspects
4. escalate to Minimum Viable Products of some Aspects
5. escalate to an early Prototype to be enhanced via Pull-Request (from a Fork) to the ME3Tweaks Mod Manager GitHub Repository
6. escalate into an actual Feature of the ME3Tweaks Mod Manager

**Comment by Mgamerz** [comment]
I'm slowly working towards a system where you can share a batch mod installer list with selected options. Users will then be required to load the specified mods it references, which can be done by going to the nexus pages - the work I've done over the years to support this (such as the nexus update system I built) can be used for this.

It's gonna take some time as I've been very busy IRL for months. Also, I have zero interest in supporting full packs - e.g. "download this 7.3 GB file, it has all the mods!" - it'd probably be more like a lot installer, maybe with automated downloads via nexus if it as premium. It's essentially a reimplementation of collections, since as far as I'm aware nexus never opened it up for other apps to use.

**Comment by zipacna** [comment]
So for most of the topics we are on the same page:
- Your (and your co-contributors) work is amazing!
- Downloads from Nexus (ideally via ME3Tweaks Mod Manager)
- Share Batch List (Kilobytes) not All Mods (Gigabytes)
- It takes time (its a hobby after all), I intent to prototype some ideas and check back in 6 months or so

The Nexus Tool, Vortex I believe, (and their Collections), similar to the Steam Workshop seem too general for the domain-specific needs of a single game/franchise (OT1-3+LE). Does Vortex or the Collections support any of the Mass Effect Mod Formats at all? Or is it (for our ME needs) only a glorified downloader (with no installation capabilities)? Not sure how open Nexus would be towards an "Extended Batch Installer for Mass Effect", but from how I read their API Reference (including the SSO Integration), the Batch Implementation (+ Extension Plan) inside the ME3Tweaks Mod Manager (or ALOT) should be ok. Since it uses / would use the API as specified and any breaking Intervention from Nexus would result in bad PR (and subsequently less premium subscriptions).

Data Quality regarding Modding Layer (ASI, manual edits, ME3Tweaks, ALOT, tpfs, shaders, savegames, ...) and Compatibility (Dependencies, Load Order, Mount Order, etc.) seems mixed on the various Nexus/Mod Pages.

So ME3Tweaks Mod Manager, even with upgrades to the Batch Mod Installer would only be able to handle mods with a `moddesc.ini`, which would "limit" Modpacks to the estimated 30-40% of Mods complying to the defacto Standard (usually the bigger content mods). Yet ca. 50-60% of all Mods are "postALOT" (usually .tpf/.mod/.mem in various folder structures) and the remainder are some odd ones (like shaders or savegames).

### My proposal would be to extend the Standard (moddesc.ini) to allow for near 100% coverage (of all ME mods) with a 2-click Install (Content via ME3Tweaks Mod Manager and Textures via ALOT).
- Would that (my smaller alternative proposal as well) be already covered by the Manifest File Format of ALOT (see Screenshot)
- or would a compatibility layer (`packdesc.ini` see Workflow Idea 2.), that **I am willing to prototype**, still be needed to reach a modding toolchain, which would allow endusers simple (full) installs and modders / modpack creators to deliver that?

![image](https://user-images.githubusercontent.com/4885295/208493527-80d84e2f-323a-45c8-8074-df146ceedf79.png)

**Comment by Mgamerz** [comment]
I would say majority of this feature has been implemented now with batch installer.
