### ISSUE TITLE
[BUG][LELAUNCHER] Bink proxy error

### ISSUE THREAD

**Issue by Patrxgt** [ME3Tweaks/ME3TweaksModManager#328]
After installation of "Unofficial LE2 Patch Launcher Video Fix" I get this error on launch:
![obraz](https://user-images.githubusercontent.com/62941214/213471979-e48ac377-9e83-4d3c-8c09-16e616989ffe.png)

From what I understand, **ME3Tweaks** tries to add DLL proxy for the launcher and replace original **bink2w64.dll**, which provokes this error, since it was made to work only with the games in the collection and not with the Legendary Edition Launcher.

**Comment by Mgamerz** [comment]
This means your launcher directory is not writable. The bink dll is made
for the launcher.

**Comment by Patrxgt** [comment]
Changing directory helped, thanks.
