### ISSUE TITLE
Tutorial typo

### ISSUE THREAD

**Issue by MarcusBrobert** [ME3Tweaks/ME3TweaksModManager#330]
There is a [typo](https://i.postimg.cc/cL0n0SK5/tutorial-typo.png) on screen 7 out of 18 in the tutorial.

The text in question:

> Import supported mods from the archive into **the your** Mod Manager mod library by selecting 'Import mods'.

Remove extra 'the':

> Import supported mods from the archive into your Mod Manager mod library by selecting 'Import mods'.

**Comment by Mgamerz** [comment]
Hi, thanks for the report. I have fixed it on the serverside where this string is stored. Users should see it within the next 24 hours.
