### ISSUE TITLE
Feature Request: Batch mod list copy function

### ISSUE THREAD

**Issue by AmunRa7** [ME3Tweaks/ME3TweaksModManager#335]
would really like to change some few things in a list while keeping the old one intact so making a copy of what works and then edit the copy is better! there's a lot of mods to mix up out there and its kinda of a pain to rebuild an entire list, so that would be really appreciated.

**Comment by Mgamerz** [comment]
In Mod Manager 8.0.1, batch queues moved into the mod library. While currently there is no such clone list functionality, you can simply copy the .biq2 file, rename it, and then open Batch Mod Installer, and you should see a duplicate list there. Right now I'm not sure how it handles this, I might attempt to improve this in the future.

**Comment by Mgamerz** [comment]
Implemented into Mod Manager 8.1 Build 128

**Comment by AmunRa7** [comment]
Thanks a ton mate 👍.
