### ISSUE TITLE
Feature Request: Various QoL Features

### ISSUE THREAD

**Issue by AudemusN7** [ME3Tweaks/ME3TweaksModManager#336]
This is a list of quality-of-life features that I think would be highly beneficial to mod developers. These features are primarily aimed to cut down the time sinks that exist within LEX's UI.

QoL Request 1 - Trashing Exports / Objects / Dialogue Nodes & Array Entry Removal

It would be a huge timesaver if there was a way to quickly trash exports, remove array entries, or objects from a level by pressing the Delete key. This could also include nodes in dialogue as well. Shift + Delete could also trash without a reference check.

While this would be a fantastic general time-saver, a specific example where this would be useful is when you need to port things between packages, but first need to clear out all references that you don't want. Say you have hundreds of exports referenced in a sequence but only you want to keep 15 for porting. You'd need to either right-click/remove from sequence for each of these, or click the Array minus button and very carefully ensure you don't accidentally remove the ones you want to keep. Instead with this feature you could just go the sequence editor and click/delete each one quickly (or even better, alt-click to drag a selection box over multiple kismet nodes to batch remove them from the sequence).

QoL Request 2 - Redirect All References

The idea here is that you can right click an export and repoint all references to another export. For example when a material import goes slightly wrong and an existing import is also ported into the package as an export, and you need to correct the reference in the binary of dozens of exports, which can be very time-consuming to do manually.

QoL Request 3 - Shift Multiple Objects

Sometimes you want to move an object, but there are other things in the level that rely on the relative positions staying the same (for example a pawn, their action station, lights and the convo stage). This QoL feature would allow you to select multiple objects in the Pathfinding Editor and shift their position as a group. (This would also potentially be great to have in LLE as well)

QoL Request 4 - Larger Colour Wheel

Often when experimenting with vector params, you need to dial in a very specific value. But because the colour wheel is quite small, this can be challenging. It would be great if the wheel was at least 2x bigger by default.

QoL Request 5 - Copy / Paste Values

Package Editor currently has the ability to copy parsed values, but it would be a great time saver if there was also the ability to paste parsed values to valid targets. This would be most useful for values that have multiple int properties such as coordinates and vectors.

QoL Request 6 - Porting Preview

When porting between packages, it would be useful to have a preview (perhaps a list? Though a visual representation in tree view would be the most idealised version of this) of all the exports/imports that will be added to the package if you proceed to clone all references. This would allow you to spot anything that's referenced that you don't want before porting into a package (especially since there's no Ctrl+Z in LEX).

QoL Request 7 - Open Highest Mounted File

This would be added under Tools in package editor. Put simply, this would open the highest mounted file with the same name (would likely require an asset database scan).

QoL Request 8 - Drag / Drop Relinking in Tree View

Instead of having to relink exports via the Metadata tab in Package Editor, you could simply click/drag an export/import within the same package to relink its instanced path. It would also be enormous bonus if you could shift+click to select multiple exports and move them all at once.

QoL Request 9 - Restore Trashed Object

While this wouldn't work on non-vanilla objects, it would be great if when restoring the export data of a vanilla trashed object, it was fully restored to where it was originally (same properties, metadata, binary, instanced path etc).

QoL Request 10 - Autosave

This feature would allow you to set an interval (for example 15 mins) in which the currently opened package is saved to an Autosaves directory, which would be highly useful if you need to revert to an earlier iteration of a file, or recover your work after a crash.

QoL Request 11 - Automatically Fix Yaw on Mesh Import

This feature would simply automatically handle correcting the yaw position on imported meshes, rather than having to manually edit the hex to reset it to 0.

**Comment by Mgamerz** [comment]
I'm not sure why you opened this in the mod manager repo.

**Comment by AudemusN7** [comment]
Because I am an idiot 🤣
