### ISSUE TITLE
Mod Manager diagnostics not looking for correct MEM texture map.

### ISSUE THREAD

**Issue by XanthosGambit** [ME3Tweaks/ME3TweaksModManager#344]
When I run a game diagnostic through the Mod Manager, I always get the following line of text: 

> Texture map file is missing: le3map.bin - was game migrated to new system or are you M3 on a different user account?

I believe this is due to MEM's texture map file actually being called "mele3.bin." So the diagnostics are looking for something that doesn't exist.

I know this is basically useless, but I figured I'd make you aware of it regardless.

**Comment by Mgamerz** [comment]
This was resolved in the March 18, 2023 build of 8.0.1.
