### ISSUE TITLE
ME3Tweaks Mod Manager cannot open coalesced.ini for ME2

### ISSUE THREAD

**Issue by levicki** [ME3Tweaks/ME3TweaksModManager#345]
Tested with latest version of ME3Tweaks Mod Manager, I have no idea if it worked before.

Trying to change console keybinds results in an error message about failed stream read and unable to open coalesced.ini.

The game is installed and works just fine.

Manage targets is showing that coalesced.ini is modified.

I am attaching it here for reference (I don't know what might have changed it and why Mod Manager is failing to load it, game has been installed recently and nothing has been done to it yet -- no mods installed or any changes made manually).

[Coalesced.zip](https://github.com/ME3Tweaks/LegendaryExplorer/files/10889692/Coalesced.zip)

**Comment by Mgamerz** [comment]
The corruption issue is due to a change in Legendary Explorer Core in regards to text encoding methods. I believe that has been fixed locally in my code but I need to do some more testing on it. It will be patched in the next bugfix update to 8.0.1.

**Comment by levicki** [comment]
@Mgamerz Thanks for letting me know, I'll hold off on trying to change console keys for now.

**Comment by Mgamerz** [comment]
This was resolved in the March 18, 2023 build of 8.0.1.
