### ISSUE TITLE
Bug: Mod Options dialog shows the previous selected items image when choosing an item in an alternate group

### ISSUE THREAD

**Issue by Herobrine24** [ME3Tweaks/ME3TweaksModManager#348]
If you have an option group with preview images, when you select an option, it will start showing the image of a not selected option with an image so long as you dont move your mouse over the group field or out of a specific field below it.

![image](https://user-images.githubusercontent.com/73685731/229280793-6889cc9e-f9d0-40b5-8e3a-286f37f1d8ca.png)

![image](https://user-images.githubusercontent.com/73685731/229280812-86b82da3-f4f5-47b8-a2f3-a723af5da03b.png)

**Comment by Mgamerz** [comment]
I've been working on stuff related to images recently and also noticed this. After digging around this seems like it's something broken in .NET 6, a remnant of when they broke and unbroke tooltips. Unfortunately I can't really fix it myself.

**Comment by Mgamerz** [comment]
Not sure if you're still working on mods these days but wondering if you could check this is still an issue with newer versions of .NET in the later version of Mod Manager.

**Comment by Herobrine24** [comment]
Still reproducible with MM9 Build 134

**Comment by Mgamerz** [comment]
Do you have a build of a mod with just a single optiongroup like the one you show? Your public version is not set up like this one. A single group with images would make this easier to troubleshoot.

**Comment by Mgamerz** [comment]
Ah nevermind, Anderson and Hackett Consistency Mod has this as well.

**Comment by Mgamerz** [comment]
Seems pretty related to https://github.com/dotnet/wpf/issues/7134, but can't be sure if it's due to the expander animation. It'd be a miracle if Microsoft fixed anything in WPF these days.

**Comment by Mgamerz** [comment]
Noticed some oddities - not sure if this is due to the debugger. As the expander closes, the contents of it seem to be being unbound or such. You can see for a frame expanded blank content - shown here
![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/2738836/1b41e3ee-7e55-4ddc-bbe0-82f55b0cc431)

I don't know if this content being here is relevant. Accessing the tooltip on the expander is very difficult because the single selector has no idea about anyone else in the group. It doesn't even know about the UI when being clicked due to data binding.

**Comment by Mgamerz** [comment]
This has been fixed in local code. After a ton of debugging on this, I gave up, and just coded in a 30ms tooltip suppression when the alternategroup non-selected item is clicked. I also fixed the weird icons showing up, I think.

**Comment by Mgamerz** [comment]
This has been improved somewhat in latest alpha, please test it. I don't think it is fully fixed, but it should be somewhat mitigated. This is a very annoying bug (and it is almost impossible to debug because you cannot use breakpoints with tooltips, as they simply close).

**Comment by Herobrine24** [comment]
Im not seeing any changes in tooltip behaviour in the June 12th build. It acts identically to MM8.

**Comment by Mgamerz** [comment]
This should actually be fixed in today's alpha build. I coded it all up and then failed to stage one of the changes.

**Comment by Herobrine24** [comment]
No longer reproducible in the June 14th build.
However, there is a different kind of odd behaviour where if you have an option group with 2 options where only one has an image, if you mouse over the one with the image and then mouse over the one without an image, so long as you dont move the mouse outside the option group or near the text of the imageless option, the image tooltip remains visible.
![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/73685731/afc9fcd4-fa76-4caf-8fc8-05ce5404a667)
