### ISSUE TITLE
MODDESC: Have an CND_ALWAYS operation

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/ME3TweaksModManager#77]
As a modder building complex mods with lots of potential options, I would like to be able to put items that are not optional as always installed in the ModDesc.  The tick should not be able to be changed and be auto applied.

For example: 
Ark Mod has many parts - the Paladin mission, and 5 different hazard maps.  If in future other people want to use the MP resources kit or enemies or just untick every other part of the mod, they see what is installing.

![image](https://user-images.githubusercontent.com/15979398/79049939-8fb3a680-7c1e-11ea-880d-43a4f080d75d.png)

**Comment by Mgamerz** [comment]
I have moved this issue to the correct repository.

**Comment by Kinkojiro** [comment]
Tested.  Works great thanks.
