### ISSUE TITLE
Adding image support for moddescs with options

### ISSUE THREAD

**Issue by JadeBarker** [ME3Tweaks/ME3TweaksModManager#79]
I believe the mod manager could benefit from supporting images during the mod installation process, much like the Vortex and old Nexus Mod Manger have for quite a while now.

When you have a mod that includes multiple options, especially ones with visual differences, users will have a better experience choosing between them, because you can have an image that swaps between the different variations as you select, or hover over them.

Here's a concept I made:
![gif](https://user-images.githubusercontent.com/54004034/79497238-92c6e200-7fe4-11ea-9efc-11ae45b003da.gif)

Here's an example from Vortex: https://wiki.nexusmods.com/index.php/How_to_create_mod_installers
![image](https://user-images.githubusercontent.com/54004034/79495484-e2f07500-7fe1-11ea-9cf4-e7da9fbe5ea6.png)

**Comment by Mgamerz** [comment]
This has been implemented in Mod Manager 6.2.
