### ISSUE TITLE
Full game restore over ALOT should remove GamerSettings.ini changes

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/ME3TweaksModManager#80]
As a user of M3 I want to fully restore a game that has previously had ALOT installed, and make sure ALOT's changes to graphical settings are also removed.

The various LOD changes that ALOT adds should be removed, otherwise you open the game subsequently and everything goes a bit pear shaped and weird.

**Comment by Mgamerz** [comment]
Good point. This comes up when targets are switched but I'm not sure if I
added it on restore.

**Comment by Mgamerz** [comment]
Can you test and validate this works?

**Comment by Kinkojiro** [comment]
Tested and works well for me3. Thanks very much.
