### ISSUE TITLE
string_nexusModsDirections

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#88]
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/0a150b35ed8af9a23b2943adcfa9cb680a2019ea/MassEffectModManagerCore/modmanager/localizations/int.xaml#L758

should match

https://github.com/ME3Tweaks/ME3TweaksModManager/blob/0a150b35ed8af9a23b2943adcfa9cb680a2019ea/MassEffectModManagerCore/modmanager/localizations/int.xaml#L763

In fact, maybe you can introduce a way to use placeholders for these kinds of references.

**Comment by Mgamerz** [comment]
Unfortunately due to xaml file restrictions, that is not possible. It's more restrictive than XML, which introduces some fun challenges.
