### ISSUE TITLE
string_dlcImportingNexusModsWatermark

### ISSUE THREAD

**Issue by HarHarLinks** [ME3Tweaks/ME3TweaksModManager#90]
https://github.com/ME3Tweaks/ME3TweaksModManager/blob/0a150b35ed8af9a23b2943adcfa9cb680a2019ea/MassEffectModManagerCore/modmanager/localizations/int.xaml#L1404

Canonical URL includes www subdomain, e.g.: https://www.nexusmods.com/masseffect3/mods/373

**Comment by Mgamerz** [comment]
This can go either way. If you want to change it to www, that's fine, but it is only a watermark.

![image](https://user-images.githubusercontent.com/2738836/80283162-e87d4780-86d2-11ea-8a8a-9cb4d4ae8837.png)

Given that these are end-users importing DLC mods... I doubt many (if any) will know or care about the difference. This info is for telemetry submission so I can catalog the mod.
