### ISSUE TITLE
TLK Compilation error

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/ME3TweaksModManager#95]
There are significant errors in the TLK compilation.  While the file is valid all the strings and randomly ordered.  Of course this means that for ME2/3 any strings with higher ones above are not read.

Here is a sample, split-tlk.
[tlk.zip](https://github.com/ME3Tweaks/ME3TweaksModManager/files/4570822/tlk.zip)

It compiles/decompiles correctly in MM5.

**Comment by Mgamerz** [comment]
Fixed by https://github.com/ME3Tweaks/ME3TweaksModManager/commit/92b65bb97ccf6fc087b14e06d15930f64b86e59e
